version: 0.2

phases:
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Downloading the serverless template
    finally:
      - echo Template and Configuration download
  build:
    commands:
      - cd ${Path}/Lambda-Code
      - aws s3 cp s3://${S3_TEMPLATE_FILE_PATH} ./template.yml
      - echo Entered the build phase...
      - echo Build and package cloudformation template
      - aws cloudformation package --template-file template.yml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file packaged-template.yml
    finally:
      - echo Build code and package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Downloading the cloudformation configuration file
      - aws s3 cp s3://${S3_CONFIGURATION_FILE_PATH} ./configuration.json
    finally:
      - echo Template and Configuration download


artifacts:
  files:
     - ./packaged-template.yml
     - ./configuration.json
  base-directory: ${Path}/Lambda-Code