AWSTemplateFormatVersion: 2010-09-09

Description: "CloudFormation template will create resources for Secrets Manager"

Parameters:
  ServiceName:
    Type: String
    Description: >-
      Enter the service name/application name this will be appended for resource names.
    Default: DB Secrets service
  ApplicationId:
    Type: String
    Description: Enter a value for tag ApplicationId
    Default: DB Secrets service
  Environment:
    Type: String
    Description: >-
      Select a value in which environment the AWS resources needs to be provisioned.
    NoEcho: true
  DbUrl:
    Description: Enter the db url
    Type: String
    Default: ''
    NoEcho: true
  DbUsername:
    Description: Enter the db username.
    Type: String
    Default: ''
    NoEcho: true
  Dbpasswd:
    Description: Enter the db Passwd.
    Type: String
    Default: ''
    NoEcho: true
  kafkaendpt:
    Description: Enter the kafka endpoint.
    Type: String
    Default: ''
    NoEcho: true
  Notificationhost:
    Description: Enter the value of notification host.
    Type: String
    Default: ''
  Notificationkey:
    Description: Enter the notification key.
    Type: String
    Default: ''
  Dbconnectionurl:
    Description: Enter the db connection url
    Type: String
    Default: ''
  Dbscrtyarg:
    Description: Enter the db security arguments value
    Type: String
    Default: ''
  Xbackkey:
    Description: Enter the db xback key value
    Type: String
    Default: ''

Resources:
  Secret:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '{{resolve:ssm:/CS/AppInfra/${Environment}/ResourceNamePrefix}}-{{resolve:ssm:/CS/AppInfra/${Environment}/Environment}}-${ServiceName}-Secret'
      Description: !Sub Secrets for service ${ServiceName} 
      SecretString: !Sub >- 
        {
          "dbDetails": {
            "db_url": "${DbUrl}",
            "db_username": "${DbUsername}",
            "db_password": "${Dbpasswd}",
            "kafka_endpoint": "${kafkaendpt}",
            "notification_host": "${Notificationhost}",
            "notification_api_key":" ${Notificationkey}",
            "database_connection_url": "${Dbconnectionurl}",
            "database_security_arguments": "${Dbscrtyarg}"
          }
        }
      Tags:
        - Key: Name
          Value: !Sub '{{resolve:ssm:/CS/AppInfra/${Environment}/ResourceNamePrefix}}-{{resolve:ssm:/CS/AppInfra/${Environment}/Environment}}-${ServiceName}-Secret'
        - Key: ApplicationRole
          Value: !Sub '${ApplicationId}-Scrt'

Outputs:
  SecretARN:
    Description: The ARN of the Secrets.
    Value: !Ref Secret